# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9bd74afe44ed6310d03863f90720a9ee"
application_url = "https://increasing-were-cited-least.trycloudflare.com"
embedded = true
name = "template"
handle = "template-52"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://increasing-were-cited-least.trycloudflare.com/auth/callback",
  "https://increasing-were-cited-least.trycloudflare.com/auth/shopify/callback",
  "https://increasing-were-cited-least.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
